### ISSUE TITLE
Complete quoting for parameters of some CMake commands

### ISSUE THREAD

**Issue by elfring** [bagder/curl#152]
Some parameters (like "[${CURL_SOURCE_DIR}/include](https://github.com/bagder/curl/blob/709cf76f6bb7dbaca14e3e8df160ccfac04dcecb/CMakeLists.txt#L72)" and "[${CMAKE_CURRENT_BINARY_DIR}/curl_config.h](https://github.com/bagder/curl/blob/20112ed8467c492a923b0ed2fb2d878c1a14ba44/lib/CMakeLists.txt#L5)") are passed to CMake commands in your build scripts without enclosing them by quotation marks. I see that these places will result in build difficulties if the contents of the used variables will contain special characters like semicolons.

I would recommend to apply [advices from a wiki article](http://cmake.org/Wiki/CMake/Language_Syntax#CMake_splits_arguments_unless_you_use_quotation_marks_or_escapes. "CMake splits arguments unless you use quotation marks or escapes.").

**Comment by snikulov** [comment]
I'll check it soon.

**Comment by bagder** [comment]
Anything?

**Comment by snikulov** [comment]
I think we should ask @bradking for this.
Personally I see no reason to put quotes around all variables/path usage.
Yes, it can help us to avoid some issues with long path in future, but no specific example/test case come into my mind right now.
Perhaps we should close this issue and solve the issues when they are arrives with exact problem description.

**Comment by bradking** [comment]
For reference, the official documentation of the cmake language command arguments is here:

 http://www.cmake.org/cmake/help/v3.2/manual/cmake-language.7.html#command-arguments

It explains how quoted arguments are always interpreted as a single value and how unquoted arguments get divided on `;` into zero or more arguments.

While the issue raised is technically correct, we commonly leave out quotes when the value is expected to be a filesystem path rather than arbitrary text or a list.  Even CMake's own source does this.  One of the reasons `;` was chosen as the list separator for unquoted argument expansion is that it is not allowed in filesystem paths on Windows and is very obscure elsewhere.

**Comment by bagder** [comment]
Thanks for the excellent feedback. Then I suggest we leave it as-is since there have not been any actual problems reported on this, nor do we really expect any.
