### ISSUE TITLE
Feature request: Be able to escape `@` prefix in `--data`

### ISSUE THREAD

**Issue by JensRantil** [bagder/curl#198]
See http://unix.stackexchange.com/q/193611/10911.

**Comment by bagder** [comment]
Yeah, I'm thinking which the best way to do that is. I figure one way is to introduce a separate option, like --data-raw "blabla" that never reads from a file. Another way would be to introduce another prefix that means "use the rest of the data raw", so that a script could prefix with that magic and then not risk reading from a file. But such a prefix would risk that there are users out there already using that prefix and then we'd break their scripts...

**Comment by JensRantil** [comment]
Yeah, I think `--data-raw "blabla"` probably is the smart way to go here.

**Comment by bagder** [comment]
That should be a really simple and yet valuable addition. Also a good chance for someone to get into curl coding...

**Comment by aavina** [comment]
Hi, I'm looking to contribute to curl and definitely interested in this request. I have a prototype of the change working but I have some questions. Would you for ever reason want to url-encode the "@"? If so, there might need to be yet another option, such as '--data-urlencode-raw'.

**Comment by bagder** [comment]
Thanks for doing this!

No, we don't need an url encoded version of raw. --data-urlencode should already be enough for that

**Comment by jay** [comment]
Landed in 6a72613.
