### ISSUE TITLE
RFC6091 support

### ISSUE THREAD

**Issue by l29ah** [bagder/curl#259]
http://curl.haxx.se/mail/lib-2015-02/0188.html
Any updates on this?

**Comment by bagder** [comment]
I missed that before. Thanks for your contribution! Here are some initial remarks:

1. it doesn't apply anymore. 
2. is "--openpgp" really needed? You must use one the other --openpgp* options anyway so why not have them imply openpgp use?
3. In the docs, please clarify that they only work when curl uses GnuTLS (and that they are added in 7.43.0)
4. There's no docs for all those new libcurl options
5. Isn't gnutls_openpgp_crt_init() simply added in a specific GnuTLS version? Just thinking that might be an easier check and would also make the openpgp options work for non-configure builds at once.
6. gtls_openpgp_connect_step3() looks like a lot of copy and paste from (the renamed) gtls_x509_connect_step3() - the big comment in the beginning is copied verbatim although seems wrong now and there's now lot of ugly code duplication.
7. I want to avoid #ifdef HAVE_* logic in src/*.c as the tool can use a different libcurl in run-time than what was available build-time. The tool can thus not know if libcurl supports OpenGPG options without checking with the lib. (either by setting an option or otherwise exporting that knowledge, perhaps in the version function)
8. Related to 7, it might be a good idea to export a bit in the version struct to allow applications to figure out if openpgp certs work.

**Comment by l29ah** [comment]
It's not my contribution, i just wanted to see why didn't it get any attention in the mailing list; you should poke the original author, tho i might want to invest some time in this if the code is orphaned.

**Comment by bagder** [comment]
Sorry, I don't hunt down patch authors for them to push for inclusion of their work. My life is too short for that. If someone wants a feature to get included in curl the person who wants that needs to remind us and push gently for it to happen. We miss things. We forget things. Sometimes we're just overloaded and can't deal with them and then we need patches and ideas to be brought back later.

If they don't come back, I take it as a sign that the submitter changed his/her mind.
