### ISSUE TITLE
Problem when i try to open the curl.exe via command line.

### ISSUE THREAD

**Issue by westor7** [bagder/curl#288]
Hello,

I have a problem when i try to open the curl.exe via a command line, it says Unknown Publisher is there any workaround fix for this so it can be run without i must force to Unblock it?

Windows 10 (10122 build)
Version: 7.42.1
Image: http://goo.gl/YACpdV

- Thanks!

**Comment by jay** [comment]
Make sure that 'Always ask before opening this file' is unchecked. If that doesn't work right-click on the file, choose 'Properties' and at the bottom of the 'General' page there should be an 'Unblock' option.

![capture](https://cloud.githubusercontent.com/assets/965580/7758979/bc0637da-ffdb-11e4-8066-968dba6c6b28.PNG)
If that doesn't work ask in a Windows 10 forum, because there may be more to it for that OS.

**Comment by westor7** [comment]
I know how to resolve this, but the problem is why the curl.exe does not include the Publisher and windows catching it as unknown.

**Comment by jay** [comment]
curl is built by third party providers. You would have to find a third party provider of curl for Windows that signs it or is willing to. You could sign it yourself if you have a code signing certificate, but if you are going to that I recommend instead you sign something you built from source yourself. The source is signed using a detached signature. For more information please refer to the [download page](http://curl.haxx.se/download.html). If you have any more questions about the curl command line tool please subscribe to the [curl-users mailing list](http://cool.haxx.se/mailman/listinfo/curl-users) and then post there.
