### ISSUE TITLE
Android 4.1 PIE support?

### ISSUE THREAD

**Issue by AlexanderOMara** [bagder/curl#333]
In short, [the Android builds](http://curl.haxx.se/gknw.net/7.40.0/dist-android/) are not compatible with Android 4.1. Attempting to run them results in the following error:

> error: only position independent executables (PIE) are supported.

This is [a pretty well known security feature](http://stackoverflow.com/questions/24818902/running-a-native-library-on-android-l-error-only-position-independent-executab) introduced in Android 4.1, which requires changes to the binary build process.

Are there any plans for the CURL binaries to support PIE/Android 4.1+?

P.S. Sorry if this is not the right place for this.

**Comment by jay** [comment]
@gknauf might know about it since he builds those. I'm closing but no objections if you reopen Gün. Alexander this is an issue tracker and questions like yours should go to a list like [curl-users](http://cool.haxx.se/mailman/listinfo/curl-users) or [curl-library](http://cool.haxx.se/mailman/listinfo/curl-library). You have to subscribe to post.
