### ISSUE TITLE
WinHttpGetProxyForUrl ?

### ISSUE THREAD

**Issue by paulharris** [bagder/curl#352]
Why is it that curl still cannot autodetect proxies on windows?

Perhaps using WinHttpGetProxyForUrl

This is a big sticking point, most of the end-user problems come from simply trying to figure out what proxy should be used (and then fixing it when proxies are changed).

There have been a couple of emails in the past that seem to be simply dropped on the floor...

eg
http://curl.haxx.se/mail/lib-2013-01/0329.html

And some notes on doing this external to curl
http://stackoverflow.com/questions/10431828/setting-the-internet-explorer-proxy-in-curl-library-requests-in-c-windows

Could be handled in-library?

**Comment by bagder** [comment]
We have to my knowledge never received any patches that bring this ability, so I'm not sure I agree anyone dropped anything. It's more like nobody ever brought us the feature. I would of course appreciate a discussion around how to do it (API wise) on the mailing list so that we can at least consider how it could work for other operating systems/environments and not make the API completely windows-specific even if an implementation could focus on that primarily.
