### ISSUE TITLE
I always get "undefined symbol: SSL_CTX_set_alpn_protos" error messages

### ISSUE THREAD

**Issue by Konstantinusz** [bagder/curl#362]
When I try to invoke cURL from my CGI application, I always get a "curl: symbol lookup error: /usr/local/lib/libcurl.so.4: undefined symbol: SSL_CTX_set_alpn_protos" error message in the Apache error_log. 
I tried to update OpenSSL (version openssl-1.0.2.d-1) and also tried to reinstall cURL from github. No success. What to do?

**Comment by bagder** [comment]
`SSL_CTX_set_alpn_protos` is used by libcurl when configure detected it should use openssl and it detected that the openssl version actually has support for ALPN.

You probably have more than one openssl library installed so that the one found and used by configure is not the same that is later used at run-time.

**Comment by Konstantinusz** [comment]
Yes, another libssl was in use, I simply renamed /opt/lampp/lib/libssl.so.1.0.0 to libssl.so.1.0.0.old, and the error message disappeared. However another error message appeared: "curl: symbol lookup error: /usr/lib/libssl.so.1.0.0: undefined symbol: EVP_idea_cbc"

**Comment by jay** [comment]
If you remove an old libssl you'll have to do the same for libcrypto I think. If that doesn't work then recall if you specified a later version of SSL to configure because then that will possibly be the least version you will need for curl to run. Check with ldd and try LD_PRELOAD and point it to the latest openssl and libcurl that you built:
~~~
export LD_PRELOAD=/usr/local/ssl/lib/libcrypto.so.1.0.0:/usr/local/ssl/lib/libssl.so.1.0.0:/usr/local/lib/libcurl.so
curl --version
~~~

**Comment by bagder** [comment]
As this isn't a curl bug really, I'm closing.

**Comment by vol7ron** [comment]
I realize this wasn't a `curl` bug, but it is curl related.  See my error, which is similar:

`~HOME/.linuxbrew/opt/curl/bin/curl: symbol lookup error: ~HOME/.linuxbrew/lib/libcurl.so.4: undefined symbol: SSL_CTX_set_alpn_protos`

In linuxbrew/homebrew, I'm guessing curl is used over wget to retrieve files.  It seems there is an SSL setting or reference that is not set in libcurl.so, which is affecting downloads.  Any ideas?

**Comment by bagder** [comment]
@vol7ron that looks like you've run curl's configure against an openssl version that is different than the one you use at run-time.

**Comment by vol7ron** [comment]
@bagder Thanks badger, so are you saying that I've updated openssl after installing curl?

**Comment by bagder** [comment]
I don't know your setup or build process so I can't tell you for sure.

It looks more like you *downgraded* openssl after you built curl, or at least you're not using OpenSSL >= 1.0.2 in run-time but you did when you built curl.

**Comment by vol7ron** [comment]
@bagder Thanks for replying - I also don't know what I did, or what was done to this box.  This is pretty much a vanilla Ubuntu 14LTS VM, with not much done to it aside from a _linuxbrew_ install and various packages installed.  I doubt that I would remove openssl, but perhaps I did - very doubtful.  But for anyone else that may come across this thread, here's what we can take away:

> **ERROR**:
> ~HOME/.linuxbrew/opt/curl/bin/curl: symbol lookup error: ~HOME/.linuxbrew/lib/libcurl.so.4: undefined symbol: SSL_CTX_set_alpn_protos
>
> **CAUSE**: 
> Curl is configured with OpenSSL settings. The error message (above) appears when OpenSSL is uninstalled or downgraded to a version prior to 1.0.2
>
> ***SOLUTION***: 
> Install OpenSSL version 1.0.2 or greater.  If using _homebrew/linuxbrew_, which will fail because it cannot install it, first remove _curl_ and then reinstall it (it should install the _openssl_ dependency first by default)

The fact that I could remove and reinstall _curl_ suggests that I had more than one on my machine.  I am not sure if it was part of Ubuntu by default, or if I used _apt-get_ to install it.  If using _homebrew/linuxbrew_ a user would need a version outside of their downloaded packages.

**Comment by bagder** [comment]
That's a problem with linuxbrew or your setup, I don't see anything that identifies a curl problem there.

**Comment by KinaMarie** [comment]
Isn't the protos a baby curl?

I have a diagram of the process.

**Comment by vol7ron** [comment]
@badger this is a late reply, but you're semi-correct. The post was geared towards people that come across the bug, but have little working knowledge of curl dependencies (like myself).

However, I should be able to maintain two versions of curl without clobbering the other. That is the idea behind  Homebrew/Linuxbrew. That said, running `apt-get update` should not cause conflicts with other installs.  So this issue may be curl-related (depending on how it finds the OpenSSL library when more than one exists), or it could be an issue for apt or homebrew.

My suspicion is that if there are multiple versions of OpenSSL then curl should use the one that it was built with, otherwise there may be an improperly set env variable?

**Comment by bagder** [comment]
curl works perfectly installed side by side with any amount of other installed curls, on numerous operating systems. Your problem is not really about curl/libcurl but how to instruct it to use your preferred set of libraries. That tends to be done with config files, environment variables and search paths. Depending on your operating system of choice. `LD_LIBRARY_PATH` is for example a common trick for classic unix style OSes.

> My suspicion is that if there are multiple versions of OpenSSL then curl should use the one that it was built with

That's not how the run-time linking of most operating systems works. We tend to use shared libraries these days and they are often updated independently of the originally built tool. Again, not a curl problem but a linker problem for when you run your program/curl.

**Comment by WordBrewery** [comment]
In case anyone else (like me) runs into this bug and finds this thread: a solution that worked for me was moving Linuxbrew closer to the end of $PATH.

**Comment by nickjhathaway** [comment]
@WordBrewery the reason for that is that linuxbrew has its own pkg-config which finds the linuxbrew libraries first, so moving linuxbrew towards the end makes it so the system pkg-config is found first and it will find the system libraries but this isn't too helpful if you still want to use the linuxbrew libraries when compiling. If you are compiling the curl library by hand one solution is to make curl set the linker run path to the openssl library found by pkg-config by setting LDFLAGS during the configure and make (it might just need to be set during configure but I set it for both steps just in case). 

First get the library directory found by pkg-config 
```bash
pkg-config --libs openssl
```
And look for the "-L" option, for my setup the output is 
```
-L/data/home/hathawan/.linuxbrew/Cellar/openssl/1.0.2l/lib -lssl -lcrypto
```

And then when compiling curl do 
```
LDFLAGS="-Wl,-rpath,/data/home/hathawan/.linuxbrew/Cellar/openssl/1.0.2l/lib" ./configure 
LDFLAGS="-Wl,-rpath,/data/home/hathawan/.linuxbrew/Cellar/openssl/1.0.2l/lib" make 
```

You can check to see if it worked by running 
```
ldd libcurl.so 
```
Which will output what the linker is finding at run time.  
```
	linux-vdso.so.1 =>  (0x00007ffe253be000)
	libssl.so.1.0.0 => /data/home/hathawan/.linuxbrew/lib/libssl.so.1.0.0 (0x00007fdad8f1c000)
	libcrypto.so.1.0.0 => /data/home/hathawan/.linuxbrew/lib/libcrypto.so.1.0.0 (0x00007fdad8abc000)
	libz.so.1 => /data/home/hathawan/.linuxbrew/lib/libz.so.1 (0x00007fdad88a4000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fdad84b4000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fdad82ac000)
	/lib64/ld-linux-x86-64.so.2 (0x00005619e2893000)
```
To see what openssl it's linking to. 

Of course, if you are already using linuxbrew you might as well just install the curl library via linuxbrew and then link to that one as linuxbrew will set the proper linker run path. As to why curl doesn't the linker run path during configure, I'm not sure but there might certain issue they are trying to avoid but I would think linking to the library you built against would be advantageous.  

Hope this helps anyone who stumbles across this thread, sorry to comment on a closed issue.

**Comment by vol7ron** [comment]
@WordBrewery For my use-case, I would prefer to use brew-installed utilities before system-installed; moving it at the end of the path wouldn't make sense for me.  

This new problem may be different from what I was encountering, which @bagder replied to and I think @nickjhathaway touched on.  While I forget the actual circumstances that led to my specific issue (and it's hard to tell how it differed from the original post), I think it had something to do with re-building curl with OpenSSL (or maybe without it) probably by using `apt-[install/update]`.  When trying to brew install a package, it tried to use `curl` that was then using the wrong libraries, I suppose.

I guess the solution would be to have something built into brew that would use the correct libraries all the time by default, without having to specify anything from the command line or add anything to the environment.
