### ISSUE TITLE
mbedTLS-2.0.0 support/conversion

### ISSUE THREAD

**Issue by hasufell** [bagder/curl#385]
Since 2.0.0 all stuff has been renamed, so mbedTLS is now a real separate library and doesn't have any polarssl references anymore. I tried to fix the stuff. Besides massive renames, a few API things have changed as well. I could get it compiling without errors, but that doesn't mean much in C. During runtime I got segfaults and gave up.

That's my work so far: https://github.com/hasufell/curl/commit/8baef8495663529004c229f4ff208dcadee619d8

The main conversion happens in `mbedtls.c`. Mind that I am no expert on any of this.

**Comment by fargly** [comment]
Is there a timeline for this enhancement?  I would love to get rid of openssl in my libcurl builds but, due to licensing, I need mbedtls 2.1.0 with it's Apache 2.0 license. I don't know the deep internals of libcurl but is there anything (i.e., prep work) that I could do to assist to allow support for mbedtls 2.1.0?

Cheers

-Kurt

**Comment by bagder** [comment]
Well, @hasufell says he gave up and nobody else has stepped up to help out. Maybe you can take his work, try it with 2.1.0 and make it into a real pull-request and then see if others are willing to help smooth out any remaining quirks?

**Comment by bagder** [comment]
@fargly has his take on this work in #441 making this issue obsolete, closing.
