### ISSUE TITLE
curl_xferinfo_callback print strange

### ISSUE THREAD

**Issue by xzzh999** [bagder/curl#489]
Hello, bigcow, I have a problem when i was doing download and print the progress information,

    curl-7.45.0   static-lib  VS2010 win 7 x64  32bit-app
    URL:  https://github.com/saghul/pyuv/archive/pyuv-1.2.0.zip

    int my_curl_xferinfo_callback(void *clientp,
								curl_off_t dltotal,
								curl_off_t dlnow,
								curl_off_t ultotal,
								curl_off_t ulnow)
     {
	     char buftest[1024];
	     sprintf(buftest,"\n process: dltotal=%ld,dlnow=%ld,ultotal=%ld,ulnow=%ld",dltotal,dlnow,ultotal,ulnow);
	     myprint(buftest);
	     return 0;
    }

and it prints follow:

                process: dltotal=148241,dlnow=0,ultotal=111974,ulnow=0
                process: dltotal=148241,dlnow=0,ultotal=111974,ulnow=0
                process: dltotal=148241,dlnow=0,ultotal=118824,ulnow=0
                process: dltotal=148241,dlnow=0,ultotal=118824,ulnow=0
                process: dltotal=148241,dlnow=0,ultotal=121340,ulnow=0
                process: dltotal=148241,dlnow=0,ultotal=121340,ulnow=0

should't dlnow as the value of ultotal ?

**Comment by jay** [comment]
You're using the wrong format specifier. `curl_off_t` size varies depending on how you build libcurl. In most cases on Windows you should have a `curl_off_t` of size 8 or 64 bits, regardless of whether you built for 32-bit or 64-bit. The proper way to handle this is use the format specifier macro `CURL_FORMAT_OFF_T` like `printf("dltotal: " CURL_FORMAT_OFF_T "\n", dltotal);`

What's happening in your example is you've specified `%ld` which is a `long int` (and in both 32-bit and 64-bit long is only size 4 in Windows) and will cause sprintf to retrieve 4 bytes, which are the lower 32-bits from `dltotal`. Then you have another `%ld` so sprintf will retrieve 4 more bytes which will be the upper 32-bits from `dltotal` since in your case `curl_off_t` is 8 bytes. So you actually don't have a ultotal, and that is why your dlnow shows in ultotal.

Here's how to do it:
~~~
int my_curl_xferinfo_callback(void *clientp,
                              curl_off_t dltotal,
                              curl_off_t dlnow,
                              curl_off_t ultotal,
                              curl_off_t ulnow)
 {
  char buftest[1024];
  sprintf(buftest, "\n process: dltotal=" CURL_FORMAT_OFF_T
                   ",dlnow=" CURL_FORMAT_OFF_T
                   ",ultotal=" CURL_FORMAT_OFF_T
                   ",ulnow=" CURL_FORMAT_OFF_T,
          dltotal,dlnow,ultotal,ulnow);
  myprint(buftest);
  return 0;
}
~~~

If you have any other libcurl questions please post them to the [curl-library mailing list](http://cool.haxx.se/mailman/listinfo/curl-library).

**Comment by xzzh999** [comment]
oh, i see. 3Q very much.
