### ISSUE TITLE
curl fails to post to web service over ssl when payload is large

### ISSUE THREAD

**Issue by dscarfo** [bagder/curl#511]
Server: Unix Server
Architecture: SPARC
Manufacturer: SUN
OS Version: 11 2 2.4.0.6.0 150517

Web Service Server: Windows 2008 R2

I have run into issues when leveraging curl to post to a windows web service endpoint over SSL when the payload size is larger than 9.3 Mb.  Anything smaller is successful, and if the connection is not using SSL it is successful.  

This behavior began when we upgraded our curl library to 7.43.0.0 or later.  Prior to that there was no error.

The 

curl --ssl -k --header "Content-Type: text/xml" --cacert certFileName
--data "@postdataFileName" https://ServerName/WebService/Service.asmx

**Comment by bagder** [comment]
That TLS library and version is your curl built to use?

Have you tried this operation against any other server to see if the problem follows? I'm curious if the particular server (version) is necessary to trigger the problem.

**Comment by dscarfo** [comment]
I have not had the opportunity to have it post to a different server with the same web service.  I have only tried from 2 different flavors of unix, sun and ibm, to a web service running in IIS on a Windows 2008 R2 server.

reply@reply.github.com At: Oct 30 2015 18:06:23" data-digest="From: reply@reply.github.com At: Oct 30 2015 18:06:23" style="">

**Comment by bagder** [comment]
... but which TLS library are your curl using? OpenSSL is the most common one but it would be good to clarify so that we can try to repeat the problem better.

**Comment by dscarfo** [comment]
1.0.1j of openssl

reply@reply.github.com At: Nov  2 2015 09:03:40" data-digest="From: reply@reply.github.com At: Nov  2 2015 09:03:40" style="">

**Comment by bagder** [comment]
I've tested uploading 100MB using the --data method to send a HTTP post over HTTPS on my test server but I can't make it fail. I tried both an OpenSSL build and a GnuTLS build but both work fine for me.

It indicates that this problem needs something in the other end to trigger and I have no similar Windows servers to test against.

**Comment by jay** [comment]
@dscarfo Maybe it's a coincidence that you had this problem around the same time you upgraded? Can you try a version you know worked with the same data for comparison? Is there an EOF in the file somewhere? That would cause the upload to be truncated. If you have access to the file you uploaded check if it ends in the EOF character 0x1A. Try `--data-binary` instead.

**Comment by jay** [comment]
Ah, I misread this. I thought you were using a Windows client and I didn't see you only had this problem with SSL. Sorry for the noise.

**Comment by dscarfo** [comment]
The client was a sun UNIX client.  The endpoint was a web service on Windows 2008 R2 server hosted in IIS.  To keep the number of variables down, the file posted was the same across the different test scenarios.  So the only thing that changed was which version of the curl and openssl that was part of the version of curl we executed, and sample data samples of various size to determine the failure point.  The issue manifested over SSL only and only with version 7.43.0.0.  

Thanks

**Comment by dscarfo** [comment]
No problem.  Always welcome the feedback.

reply@reply.github.com At: Nov  6 2015 02:36:50" data-digest="From: reply@reply.github.com At: Nov  6 2015 02:36:50" style="">

**Comment by jay** [comment]
The litmus test should be posting the same data from both versions of curl and then comparing. It is possible that this just happened around the same time you upgraded, and may have nothing to do with the upgrade.

**Comment by dscarfo** [comment]
Perhaps I was not clear, the test was posting the same data from both versions of curl.  There were several test data which were of different size payloads but each test was conducted against several versions of curl.  That is how I determined which version of curl had an issue, and what the size limitation was.  A synopsis of the tests conducted were:
               
Version   curl     5 Mb     5 Mb      9.4 Mb   9.4 Mb     
          version  File File File File
                   SSL      NonSSL    SSL      NonSSL     
201504v01 7.21.2.7 Pased    Pased     Pased    Pased      
201507v00 7.43.0.0 Pased    Pased     Failed   Pased      

There were variations to the tests performed mostly around the version of SSH to leverage, and several different payload sizes to isolate the size failure, as well as the current version of curl, 7.45.0, and earlier versions.  Regardless the result was the same.  

Regards,

reply@reply.github.com At: Nov  6 2015 13:13:17" data-digest="From: reply@reply.github.com At: Nov  6 2015 13:13:17" style="">

**Comment by jay** [comment]
Thanks for that additional information, that's very strange. Would you be able to run a git bisect to isolate the commit that may be responsible for what you are experiencing? 7.21 is several years old and there's been about 14,000 commits since then :) The steps are
~~~
mkdir -p test && cd test
git clone https://github.com/bagder/curl.git
cd curl
git bisect start
# Mark a commit or tag you know is bad.
git bisect bad curl-7_45_0
# Mark a commit or tag you know is good. 
git bisect good curl-7_21_0 ?? or whatever
# Git bisect starts.
# Repeat the process below for each commit it checks out.
#
# If any of the build steps fail you can use 'git bisect skip' to skip that commit and try another.
make distclean    # Ignore 'unknown target' messages
./buildconf
./configure <however you typically configure>
make
# No need to install, libtool should package a version for you that loads the just built libcurl:
src/curl -V
# Send your large file:
src/curl --ssl -k --header "Content-Type: text/xml" --cacert certFileName --data "@postdataFileName" https://ServerName/WebService/Service.asmx
# Based on whether the upload was successful or truncated mark the commit good or bad:
# git bisect good
# git bisect bad
# or 'git bisect skip' if it's just entirely unsuccessful (ie something else is broken)
# After marking good/bad/skip git will load the next commit to try.
# Go back to 'make distclean' and repeat.
~~~
The process should take about 13 builds, not including any skipped bad builds.

**Comment by dscarfo** [comment]
Ok Jay.  Will do and revert back with the results.  I will not be able to get to it until next weeks.

Have a good weekend and thanks.

**Comment by bagder** [comment]
No info provided. Closing until more arrives.

**Comment by patrikhson** [comment]
Hi,

Ithink you'll be happy to read that amazing article I've just found on the web, here it is  <http://stofofrulu.s2piddy.net/xylzk>

All the best, paf@frobbit.se
