### ISSUE TITLE
Installing the curl 7.4.5.0 on Ubuntu 14.04 unsuccessful

### ISSUE THREAD

**Issue by LeoMustafa** [bagder/curl#516]
when i fished install the curl 7.4.5 and i type curl --version,but i just get curl 7.36.0 (i686-pc-linux-gnu),what reason is this ?

**Comment by jay** [comment]
I have curl 7.45 installed in Ubuntu 14 and it works fine. If you installed curl to the default location (/usr/local) and that is in your PATH (by default it should be) then It's likely that what you are seeing is due to the bash shell's path caching. The first time after you open the shell and run a command in the shell by default it caches the path. Since you already have the curl tool installed with Ubuntu it cached that path when you ran curl. Try `/usr/local/bin/curl -V` and confirm the curl 7.45.0 is installed, and if it is then try `hash -d curl` to remove the old cached curl path (likely /usr/bin). Or just close out terminal and reopen it. Now you should be able to type `curl -V` without a path and see the version you installed.

In the future if you have any questions about curl or libcurl please use one of the [mailing lists](http://curl.haxx.se/mail/), this is an issue tracker for reporting bugs and feature requests, etc.

**Comment by LeoMustafa** [comment]
Thank you very much,i have already solved it.
