### ISSUE TITLE
Some Windows 7.46.0 packages potentially containing malware

### ISSUE THREAD

**Issue by sandersaares** [bagder/curl#583]
Not sure if this is the right place to report it but I was not able to find any obvious contact info on the website, so here it is.

Suspect URLs:

* bintray.com/artifact/download/vszakats/generic/curl-7.46.0-win64-mingw.7z
* bintray.com/artifact/download/vszakats/generic/curl-7.46.0-win32-mingw.7z

VirusTotal links: 

* https://www.virustotal.com/en/file/75916c7b81445e23a49f9a958ce3af8e8ea13d732d0ee8ca1da6f1d01ba3a729/analysis/1451274235/
* https://www.virustotal.com/en/file/894f4d3e79bc4684fda1919ff53cd04e81bdc54916b3f61817a1be39a0486800/analysis/1451287274/

The positive matches are from some rather obscure scanners, so perhaps false positives? However, [the file was reported on StackExchange as having different content some weeks ago](https://security.stackexchange.com/questions/109113/why-would-a-website-serve-potential-malware-over-http-but-a-good-version-over-ht/109121#109121) which lends some credibility to a potential compromise.

**Comment by jay** [comment]
cc @vszakats

**Comment by vszakats** [comment]
* Content changes as the package is rebuilt using updated dependencies, so it is normal in the current setup (in case of 7.46.0, nghttp2 was enabled, then updated to 1.5.0, then a `libcurl.dll` build bug fixed, caused by a missing option in the nghttp2 build process)
* As for malware, it's most definitely false positive unless the CI host, the C compiler, or the vendored `mingw32-make.exe` is infected. None of this is likely, but auditable by anyone nevertheless.
* The whole build process is auditable via public [log](https://ci.appveyor.com/project/vsz/harbour-deps/build/1.0.231) and all scripts are [open](https://github.com/vszakats/harbour-deps) as well. Anyone is welcome to dissect/audit it and/or send pull requests or suggestions (within the limit the result still fits my purposes)
* VirusTotal claims to be a tool meant for scanner manufacturers to enhance their engines, so if anyone has confirmed if these packages are or are not malicious, this fact can be marked as such on the results page.

**Comment by vszakats** [comment]
My answer on Stack Exchange: https://security.stackexchange.com/a/109130/37202

**Comment by sandersaares** [comment]
Thanks for fast response! That clears it up.

Though I must say that having the content for the same version of the package change over time is rather unexpected! I would never have guessed that the 7.46.0 I download one week might not be the 7.46.0 I download the next week.

**Comment by vszakats** [comment]
Yes, I'm aware of it being unusual (and that it may break automated scripts that expect the package to verify against the hash of a particular build).

A sequence number could be introduced to get around that in the future, though for simplicity and to have stable download URLs, I didn't implement such a solution yet. One of the goals of these builds was to make the binaries "agile" by following not just major `curl` releases, but major releases of it's dependencies as well. Speaking of OpenSSL, this aspect is IMO crucial. (even though last time `curl` and OpenSSL releases nearly coincided.)

**Comment by vszakats** [comment]
I've [commited](https://github.com/vszakats/harbour-deps/commit/e2a506a6ca7d071b9ceba96b8de467fbbc018651) a fix that drops the file `mk-ca-bundle.vbs` from my curl binary distro packages, resolving the false positive hit on VirusTotal ("Dropper.Inor.VBS.7" by product "Zillya").

I've also implemented automatic submission of generated binary packages to VirusTotal.
